admin_user:
    resource: "@AdminBundle/Controller/UserController.php"
    type:     annotation

admin_thing:
    resource: "@AdminBundle/Controller/ThingController.php"
    type:     annotation

admin_street:
    resource: "@AdminBundle/Controller/StreetController.php"
    type:     annotation

admin_area:
    resource: "@AdminBundle/Controller/AreaController.php"
    type:     annotation

admin_city:
    resource: "@AdminBundle/Controller/CityController.php"
    type:     annotation

admin_country:
    resource: "@AdminBundle/Controller/CountryController.php"
    type:     annotation

admin_find:
    resource: "@AdminBundle/Controller/FindController.php"
    type:     annotation

admin_lost:
    resource: "@AdminBundle/Controller/LostController.php"
    type:     annotation

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

personal_area:
    resource: "@PersonalAreaBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
