<?php

namespace AdminBundle\Repository;


/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByParentId($country_id){
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AdminBundle:City c WHERE c.countryId = :country_id")
            ->setParameter('country_id', $country_id)
            ->getArrayResult();

    }
}
