<?php

namespace AdminBundle\Repository;


/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCityByCountryId($country_id){
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AdminBundle:City c WHERE c.countryId = :country_id")
            ->setParameter('country_id', $country_id)
            ->getArrayResult();

    }

    public function getCityByCountryName($country_name){
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AdminBundle:City c WHERE c.countryId = (SELECT k FROM AdminBundle:Country k WHERE k.country = :country)")
            ->setParameter('country', $country_name)
            ->getArrayResult();

    }
}
