<?php

namespace AdminBundle\Repository;

/**
 * FindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FindRepository extends \Doctrine\ORM\EntityRepository
{
}
