<?php

namespace AdminBundle\Repository;

/**
 * LostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LostRepository extends \Doctrine\ORM\EntityRepository
{
}
