<?php

namespace AdminBundle\Repository;

/**
 * ThingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getThings(){
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM AdminBundle:Thing t')
            ->getArrayResult();
    }
}
